const CodeBlock = () => {
  return (
    <div className='flex-1 overflow-x-auto text-[16px]'>
                    <pre className='text-white'><span >&lt;<span className="pl-ent">div</span> <span className="pl-e">className</span><span className="pl-k">=</span><span className="pl-s"><span className="pl-pds">&quot;</span>w-1/2 flex flex-col border-l border-darkgray-100<span className="pl-pds">&quot;</span></span>&gt;</span></pre>
                    <pre className='text-white'><span >  &lt;<span className="pl-ent">div</span> <span className="pl-e">className</span><span className="pl-k">=</span><span className="pl-s"><span className="pl-pds">&quot;</span>h-16 border-b border-darkgray-100 flex justify-center relative<span className="pl-pds">&quot;</span></span>&gt;</span></pre>
                    <pre className='text-white'><span >    &lt;<span className="pl-ent">Image</span><span className="pl-s"> <span className="pl-e">src</span><span className="pl-k">=</span>"/Logo.svg" <span className="pl-e">alt</span><span className="pl-k">=</span>"Logo W for William" <span className="pl-e">width</span><span className="pl-k">=</span><span className="pl-o">&#123;</span>33<span className="pl-o">&#125;</span> <span className="pl-e">height</span>=<span className="pl-o">&#123;</span>19<span className="pl-o">&#125;</span></span>&gt;</span></pre>
                    <pre className='text-white'><span >    &lt;<span className="pl-ent">Image</span><span className="pl-s"> <span className="pl-e">src</span><span className="pl-k">=</span>"/Hamburger_LG.svg" <span className="pl-e">alt</span><span className="pl-k">=</span>"Hamburger icon" <span className="pl-e">width</span><span className="pl-k">=</span><span className="pl-o">&#123;</span>24<span className="pl-o">&#125;</span> <span className="pl-e">height</span><span className="pl-k">=</span><span className="pl-o">&#123;</span>24<span className="pl-o">&#125;</span> <span className="pl-e">style</span><span className="pl-k">=</span><span className="pl-o">&#123;</span><span className="pl-o">&#123;</span>position: "absolute", left: "24px", top: "50%", transform: "translateY(-50%)"<span className="pl-o">&#125;</span><span className="pl-o">&#125;</span></span>&gt;</span></pre>
                    <pre className='text-white'><span >   &lt;/<span className="pl-ent">div</span>&gt;</span></pre>
                    <pre className='text-white'><span >   &lt;<span className="pl-ent">div</span> <span className="pl-e">className</span><span className="pl-k">=</span><span className="pl-s"><span className="pl-pds">&quot;</span>flex-1 bg-darkgray-300 flex justify-center items-center<span className="pl-pds">&quot;</span></span>&gt;</span></pre>
                    <pre className='text-white'><span >    &lt;<span className="pl-ent">Image</span> <span className="pl-e">src</span>=<span className="pl-s"><span className="pl-pds">&quot;</span>/picture.png<span className="pl-pds">&quot;</span></span>&gt;</span></pre>
                    <pre className='text-white'><span >           </span><span className="pl-e">width</span><span className="pl-k">=</span><span className="pl-o">&#123;</span>400<span className="pl-o">&#125;</span></pre>
                    <pre className='text-white'><span >           </span><span className="pl-e">height</span><span className="pl-k">=</span><span className="pl-o">&#123;</span>400<span className="pl-o">&#125;</span></pre>
                    <pre className='text-white'><span >           </span><span className="pl-e">alt</span><span className="pl-k">=</span><span className="pl-s"><span className="pl-pds">&quot;</span>Picture of myself<span className="pl-pds">&quot;</span></span></pre>
                    <pre className='text-white'><span >    /&gt;</span></pre>
                    <pre className='text-white'><span >   &lt;/<span className="pl-ent">div</span>&gt;</span></pre>
                    <pre className='text-white'><span >&lt;/<span className="pl-ent">div</span>&gt;</span></pre>
                  </div>
  )
}

export default CodeBlock